client/app.js, client/components/NavbarMain.js, client/components/checkout-item.js, client/components/checkout.js, client/store/checkout.js, client/store/index.js, package.json, public/index.html
created  a redux store for checkout and added a nav
=> Johnny checkout slice

client/components/auth-form.js, client/components/user-home.js, package-lock.json, package.json, server/db/models/user.js
**Users Slice**
Front End
Back End
=> feat : added login ui

client/components/SingleProduct.js, client/store/index.js, client/store/singleProduct.js
**Single products slice** 
create slice for single product
Front End
- [x ] Create front end component 
- [ x] Create Store
- [ x] import store to combo reducer
Back End
---
=> Feat: Single Product View

client/components/Subtotal.js, client/components/checkout-item.js, client/components/checkout.js, client/routes.js, client/store/checkout.js, public/cart.css, public/index.html
added styling for checkout page
---
=> feature: added css to checkout

client/components/AllProducts.js, client/routes.js, package-lock.json, public/style.css, script/seed.js, server/api/carts.js, server/api/index.js, server/db/models/cart.js, server/db/models/cartItems.js, server/db/models/index.js
=> Tommy working on cart model

.gitignore, client/components/allUserAdminView.js, client/routes.js, client/store/allUsersAdminView.js, client/store/index.js, server/auth/google.js
=> fix: oauth api key hidden

client/components/NavbarMain.js, client/components/Subtotal.js, client/components/checkout-item.js, client/components/checkout.js, client/store/checkout.js, public/cart.css, server/api/carts.js
added a sticky top, inc, and dec button for checkout page
=> feature: add inc and dec button

client/components/AllProducts.js, client/components/ProductDescription.js, server/db/models/product.js
=> added: guest cart saved on localstorage

.travis.yml, client/components/AllProducts.js, server/db/models/product.js
=> fix: travis db issue

client/components/user-home.spec.js, client/store/user.spec.js
=> fix: disable test

client/components/AllProducts.js, client/components/ProductDescription.js, package-lock.json, package.json, public/index.html, public/product-description.css, public/style.css
=> feature: added all products css styling and tweaked button locations

client/components/AllProducts.js, public/product-description.css, script/seed.js, server/db/models/index.js, server/db/models/review.js
=> added: new data + css styling

client/components/ProductDescription.js, client/routes.js, client/store/adminProduct.js, server/api/adminProduct.js
=> Williams user slice

script/seed.js, server/db/models/cart.spec.js, server/db/models/cartitems.spec.js, server/db/models/product.spec.js, server/db/models/review.spec.js
=> added: all model testspecs except cartItems

public/style.css
=> fixed css styling on preview and category buttons

client/components/AllProducts.js, client/components/addProductAdmin.js, client/store/adminProduct.js, public/style.css, server/api/adminProduct.js
bug fix for middle ware and added add new product
=> feat:  add new product admin

client/components/newauth-form.js, client/components/user-home.js, client/components/user-home.spec.js, client/routes.js, client/store/user.spec.js
=> William UI

client/components/Subtotal.js, client/components/checkout-item.js, client/components/checkout.js, client/store/checkout.js, public/cart.css, script/seed.js, server/api/carts.js
=> bug fix: fixed rounding errors and carts are persistent

client/components/ProductDescription.js, client/store/checkout.js, script/seed.js, server/api/carts.js, server/api/products.js
=> added: add cart functionality on all products

client/components/ProductDescription.js, client/components/SingleProduct.js
=> added: add cart feature on single product page

server/api/products.spec.js
=> chore: working product route test specs

client/components/NavbarMain.js, client/components/Subtotal.js, client/components/checkout.js, client/store/checkout.js
=> bug fix: no longer shows a price if cart is empty

client/components/CheckoutProcess/AddressForm.js, client/components/CheckoutProcess/Checkout.js, client/components/CheckoutProcess/PaymentForm.js, client/components/CheckoutProcess/Review.js, client/components/NavbarMain.js, client/components/checkout.js, client/routes.js
=> feat: login route

public/product-description.css, script/seed.js
=> fixed: jewelry spelling and centered search bar

client/components/CheckoutProcess/Checkout.js
=> changed copyright
